version: '3.3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - ./userdata/work:/home/jovyan/work
      - ./userdata/data:/home/jovyan/data
    command: start.sh jupyter notebook --NotebookApp.base_url='/notebook/' --NotebookApp.token=''
    restart: always

  dashboard:
    image: jojomi/hugo
    volumes:
      - ./dashboard/src:/src
      - ./dashboard/output:/output
    environment:
      - HUGO_WATCH=false
    restart: always

  server:
    image: jojomi/nginx-static
    volumes:
      - ./dashboard/output:/var/www
    restart: always
    depends_on:
      - "dashboard"

  proxy:
    image: nginx
    links: 
      - jupyter
      - server
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/letsencrypt.crt:/data/cert.crt
      - ./server/letsencrypt.key:/data/key.key
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - "jupyter"
      - "server"
