version: '3.3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - ./:/work
    command: start.sh jupyter notebook --NotebookApp.base_url='/notebook/' --NotebookApp.token=''
    restart: always

  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard/src:/src
      - ./dashboard/output:/output
    environment:
      - HUGO_WATCH=false
      - HUGO_BASEURL=
    restart: always

  server_dashboard:
    image: jojomi/nginx-static
    volumes:
      - ./dashboard/output:/var/www
    restart: always
    depends_on:
      - "dashboard"

  proxy:
    image: nginx
    links: 
      - jupyter
      - server_dashboard
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/carocloud.crt:/data/cert.crt
      - ./server/carocloud.key:/data/key.key
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - "jupyter"
      - "server_dashboard"
